#!/bin/bash

if [ ! $2 ] ; then
  echo Usage is \$
  ./importdb ri 2020-12-28T19_23Z.sql
  exit 1
fi

dbname=${1}
dbuser=postgres
exampleDir=examples

infile=${2}
inpath=./${exampleDir}/${1}/sql/${infile}

outfile=${2//sql/clean.sql}
outpath=./${exampleDir}/${1}/sql/${outfile}


dropdb ${dbname}
createdb --owner=${dbuser} ${dbname}

# rm uploads/*

echo Working...

# cares_reporter_bi26_user is from ri
# cares_reporter_a2n0_user is from oh
junk="cares_reporter_bi26_user|cares_reporter_a2n0_user|\
tiger|topology|geometry|geography|spatial|raster|pg_similarity|postgis"
# echo ${junk}

egrep -v ${junk} ${inpath}\
 | pcre2grep -M -v '(\n\n\\\.)'\
 > ${outpath}

psql ${dbname} ${dbuser} < ${outpath}
