#!/bin/bash

echo Working...

infile=${1}
outfile=${1//sql/clean.sql}

# cares_reporter_bi26_user is from ri
# cares_reporter_a2n0_user is from oh
junk="cares_reporter_bi26_user|cares_reporter_a2n0_user|\
tiger|topology|geometry|geography|spatial|raster|pg_similarity|postgis"
# echo ${junk}

egrep -v ${junk} ./${infile}\
 | pcre2grep -M -v '(\n\n\\\.)'\
 > ${outfile}

